//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Linehaul_Helper.Localization {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Linehaul_Helper.Localization.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string AboutPageTitle {
            get {
                return ResourceManager.GetString("AboutPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linehaul Helper.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jobs.
        /// </summary>
        internal static string JobsPageTitle {
            get {
                return ResourceManager.GetString("JobsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track.
        /// </summary>
        internal static string ParcelTrackingPageButtonText {
            get {
                return ResourceManager.GetString("ParcelTrackingPageButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your tracking number (ie: AA0309024).
        /// </summary>
        internal static string ParcelTrackingPageEntryPlaceholder {
            get {
                return ResourceManager.GetString("ParcelTrackingPageEntryPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking.
        /// </summary>
        internal static string ParcelTrackingPageTitle {
            get {
                return ResourceManager.GetString("ParcelTrackingPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string PlateNumberPageButtonOk {
            get {
                return ResourceManager.GetString("PlateNumberPageButtonOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Error.
        /// </summary>
        internal static string PlateNumberPageButtonReportError {
            get {
                return ResourceManager.GetString("PlateNumberPageButtonReportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string PlatesPageButtonErrorCancel {
            get {
                return ResourceManager.GetString("PlatesPageButtonErrorCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add It.
        /// </summary>
        internal static string PlatesPageButtonErrorConfirm {
            get {
                return ResourceManager.GetString("PlatesPageButtonErrorConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit number not found in database.
        ///
        ///Contact info@cellninja.ca to add this unit..
        /// </summary>
        internal static string PlatesPageButtonErrorMessage {
            get {
                return ResourceManager.GetString("PlatesPageButtonErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string PlatesPageButtonErrorTitle {
            get {
                return ResourceManager.GetString("PlatesPageButtonErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get plate number.
        /// </summary>
        internal static string PlatesPageButtonText {
            get {
                return ResourceManager.GetString("PlatesPageButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter truck or trailer number (ie: 7501).
        /// </summary>
        internal static string PlatesPageEntryPlaceholder {
            get {
                return ResourceManager.GetString("PlatesPageEntryPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last updated on {0:d} {0:t}.
        /// </summary>
        internal static string PlatesPageLastUpdated {
            get {
                return ResourceManager.GetString("PlatesPageLastUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Plates.
        /// </summary>
        internal static string PlatesPageTitle {
            get {
                return ResourceManager.GetString("PlatesPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string PlatesPageUpdateButtonText {
            get {
                return ResourceManager.GetString("PlatesPageUpdateButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch Location.
        /// </summary>
        internal static string SwitchLocationPageTitle {
            get {
                return ResourceManager.GetString("SwitchLocationPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.dicom.com/en/dicom/tracking/result.
        /// </summary>
        internal static string TrackingBaseUrl {
            get {
                return ResourceManager.GetString("TrackingBaseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new unit.
        /// </summary>
        internal static string UnitInfoCreationPageTitle {
            get {
                return ResourceManager.GetString("UnitInfoCreationPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warehouse Location.
        /// </summary>
        internal static string WarehouseLocationPageTitle {
            get {
                return ResourceManager.GetString("WarehouseLocationPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        internal static string WeightPageTitle {
            get {
                return ResourceManager.GetString("WeightPageTitle", resourceCulture);
            }
        }
    }
}
